# Generated by Django 3.1.2 on 2020-11-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.TextField()),
                ('email', models.TextField(default='salilsanat@gmail.com')),
                ('otp', models.CharField(default='123456', max_length=6)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
