# Generated by Django 3.1.2 on 2020-11-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0004_auto_20201127_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileotp',
            name='email',
            field=models.TextField(),
        ),
    ]
