# Generated by Django 3.1.3 on 2020-11-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0007_auto_20201127_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileotp',
            name='otp',
            field=models.CharField(default=222828, max_length=6),
        ),
    ]
