# Generated by Django 3.1.3 on 2020-11-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0008_auto_20201127_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileotp',
            name='otp',
            field=models.CharField(default=601459, max_length=6),
        ),
    ]
