# Generated by Django 3.1.3 on 2020-11-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0010_auto_20201128_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileotp',
            name='otp',
            field=models.CharField(default=932506, max_length=6),
        ),
    ]
