# Generated by Django 3.1.3 on 2020-11-28 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0011_auto_20201128_1151'),
        ('NewsApp', '0011_auto_20201128_1231'),
    ]

    operations = [
    ]
