# Generated by Django 3.1.3 on 2020-11-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0012_merge_20201128_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileotp',
            name='phone',
            field=models.CharField(default=62456256, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profileotp',
            name='otp',
            field=models.CharField(default=880871, max_length=6),
        ),
    ]
