# Generated by Django 3.1.3 on 2020-11-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0013_auto_20201128_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileotp',
            name='otp',
            field=models.CharField(default=404743, max_length=6),
        ),
    ]
