# Generated by Django 3.1.3 on 2020-11-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0014_auto_20201128_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileotp',
            name='otp',
            field=models.CharField(default=490050, max_length=6),
        ),
    ]
