# Generated by Django 3.1.3 on 2020-11-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0015_auto_20201128_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileotp',
            name='otp',
            field=models.CharField(default=445861, max_length=6),
        ),
    ]
